{
 "title": "PsyApp Business Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "New Clients Daily",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "new_clients_daily_value", "legendFormat": "New Clients" }
   ]
  },
  {
   "title": "Appointments Daily",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "appointments_daily_value", "legendFormat": "Appointments" }
   ]
  },
  {
   "title": "Income Daily",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "analytics_daily_value", "legendFormat": "Income" }
   ]
  }
 ]
}